name: Load all vocabs
on:
  workflow_dispatch:
jobs:
  load_all_vocabs:
    runs-on: ubuntu-latest
    steps:
      - name: Bring in repo - master branch
        uses: actions/checkout@v1
        with:
          ref: master
      - name: Install Python dependencies
        run: |
          python -m pip install -U pip
          pip install -r scripts/requirements.txt
      - name: Load all vocabs
        env:
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          BASE_DB_URI: ${{vars.BASE_DB_URI_PROD}}
        run: |
          echo 'Run load script...'
          python scripts/load_all_vocabs.py