name: Handle updated vocabs
on:
  push:
    branches: [ master ]

  workflow_dispatch:
jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - name: Bring in repo - master branch
        uses: actions/checkout@v1
        with:
          ref: master
      - name: install Python dependencies
        run: |
          python -m pip install -U pip
          pip install -r scripts/requirements.txt
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: ','        
      - name: detect file changes
        env:
            DB_USERNAME: ${{secrets.DB_USERNAME}}
            DB_PASSWORD: ${{secrets.DB_PASSWORD}}
            BASE_DB_URI: ${{vars.BASE_DB_URI_PROD}}
            WEBSITE_URL: ${{vars.WEBSITE_URL_PROD}}
        run: |
          echo 'Run update script...'
          a=${{steps.file_changes.outputs.files_added}}
          m=${{steps.file_changes.outputs.files_modified}}
          r=${{steps.file_changes.outputs.files_removed}}
          if [ -z $a ]; then a="x"; fi
          if [ -z $m ]; then m="x"; fi
          if [ -z $r ]; then r="x"; fi
          python scripts/update_vocabs.py -a $a -m $m -r $r
